application.version: ${version}

logging:
  logback.rollingpolicy.max-history: 10
  file:
    name: \${user.home}/.komga/komga.log
  level:
    org.apache.activemq.audit.message: WARN

komga:
  libraries-scan-cron: "0 */15 * * * ?"
  trash-emptying-cron: "0 0 0 ? * * "
  libraries-scan-directory-exclusions:
    - "#recycle"
    - "@eaDir"
  database:
    file: \${user.home}/.komga/database.sqlite

spring:
  #  cache:
  #    caffeine-spec: maximumSize=500,expireAfterWrite=300s
  datasource:
    url: jdbc:h2:~/.komga/database.h2
    username: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
  resources:
    add-mappings: false
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    mixed: true
  thymeleaf:
    prefix: classpath:/public/
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
  artemis:
    embedded:
      persistent: true
      data-directory: \${user.home}/.komga/artemis

server:
  servlet.session.timeout: 7d
  forward-headers-strategy: framework
  shutdown: graceful

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      roles: ADMIN
      show-details: when_authorized
  metrics:
    export:
      influx:
        enabled: false
springdoc:
  group-configs:
    - group: REST API
      paths-to-match: /api/**
    - group: OPDS
      paths-to-match: /opds/**
  swagger-ui:
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
